#!/bin/bash

###################################
#
# Created by Rohan M and Yashas V.
# Public domain.
# Simple wrapper for c/c++ compilers.
#
###################################

if [[ "$CC" == "" ]]; then
	echo "Error: Set default c compiler"
	echo "Try: export CC=____"
	exit 1
fi

SOURCE=$1
NAME=$2

source ./ZBUILD &> /dev/null 

if [[ "$SOURCE" == "" ]]; then
	echo "Error: Provide source file as first argument"
	exit 2
fi

if [[ "$NAME" == "" ]]; then 
	echo "Error: Provide project name as second argument"
	exit 2
fi

shift 2

start=`date +%s.%N`
$CC $SOURCE $FLAGS $@ -o $NAME &> /tmp/$NAME".err.cc"
RETURN=$?
finish=`date +%s.%N`
TIME=$(echo "$finish - $start" | bc -l | cut -c -5)

cat /tmp/$NAME".err.cc" | grep -E 'error|warning' | sed 's/error: //g;s/$/\n/;s/: /:\n/;' > $NAME.err.cc
#rm /tmp/$NAME".err.cc"

if [[ "$RETURN" == "0" ]]; then
	echo "-- Compiled. ("$TIME"s) --"
	stat ./$NAME &> /dev/null && ./$NAME
else
	echo "-- Failed. ("$TIME"s) --"
fi
